### ISSUE TITLE
Why same display for iPad and iPhone?

### ISSUE THREAD

**Issue by K232** [jamesmontemagno/MyShoppe#10]
Hi James,
one question regarding the different design for iPad and iPhone: With iPad simulator it shows "Select a shop" at the right. But when I select a shop, also the list on the left disappears and the selected shop is shown in fullscreen. Wouldn't it be better user experience if the shop is just shown on the right, keeping the list of shops on the left so the user could easily select another shop without using the back button? I would expect something like this:
<img width="767" alt="myshoppe3" src="https://cloud.githubusercontent.com/assets/685016/14530231/5bc7890c-0258-11e6-837e-78115f454f0d.png">
But I wonder why it's so hard to find any samples for Xamarin using different displays for iPad and iPhone? None of the official prebuilts at https://www.xamarin.com/prebuilt have different displays. So do I have a mistake here? Is this the expected behaviour that nowadays an iPad should show everything in the same style like the iPhone, just larger?
Many thanks!

**Comment by jamesmontemagno** [comment]
I think I fixed this bug in the code.
