### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by VashJuan** [jamesmontemagno/MyShoppe#12]
I've Visual Studio 2015 Pro on a Winodws 10 Pro machine, installed Xamarin + Windows SDK, JAVA SDK, and vs_Emulator, and likely more things & signed up for the Xamarin account & logged in from Visual Studio. (I've yet to allow Xamarin through my firewall.) I easily could have missed other steps, but if so am not aware what else needs to be done.

I can build and run the "BlankAndroidApp" from New Project | Templates | Visual C# | Android | Blank App (Android), using .NET Framework 4.0. I finally got the Hyper-V emulator working. Now on to My Shoppe which looks great for my needs!

Anyway I try new project from source control, use https://github.com/jamesmontemagno/MyShoppe, download a copy, and set MyShop.Android as the Startup Project (I'm not interested in Mac or universal apps for now) and select Build. NuGet downloads lots of dependencies, but then I get lots of errors.

Obviously I'm new to this, so presume there are some simple mistakes I'm making, but am unsure whether there are dependencies or targets that need to be changed? Thanks for any suggestions!

Output window displays:

1>------ Build started: Project: MyShop, Configuration: Debug Any CPU ------
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\FeedbackViewModel.cs(29,30,29,32): warning CS0168: The variable 'ex' is declared but never used
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(13,4,13,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(17,4,17,16): error CS0103: The name 'PickerRating' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(18,4,18,21): error CS0103: The name 'PickerServiceType' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(20,4,20,15): error CS0103: The name 'PickerStore' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(35,6,35,17): error CS0103: The name 'PickerStore' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs(37,20,37,22): warning CS0168: The variable 'ex' is declared but never used
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs(14,4,14,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs(30,4,30,9): error CS0103: The name 'MyMap' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs(32,4,32,9): error CS0103: The name 'MyMap' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StoresPage.xaml.cs(18,4,18,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs(13,4,13,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs(15,4,15,19): error CS0103: The name 'ButtonFindStore' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs(25,17,25,26): error CS0103: The name 'HeroImage' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs(28,4,28,23): error CS0103: The name 'ButtonLeaveFeedback' does not exist in the current context
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\FeedbackViewModel.cs(81,30,81,32): warning CS0168: The variable 'ex' is declared but never used
1>C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\StoresViewModel.cs(105,30,105,32): warning CS0168: The variable 'ex' is declared but never used
2>------ Build started: Project: MyShop.Android, Configuration: Debug Any CPU ------
2>  No way to resolve conflict between "PCLStorage, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64" and "PCLStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64". Choosing "PCLStorage, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64" arbitrarily.
2>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.IO.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Net.Primitives.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "PCLStorage, Culture=neutral, PublicKeyToken=286fe515a2c35b64" from Version "1.0.0.0" [] to Version "1.0.2.0" [C:\Users\John\Source\Repos\MyShoppette\MyShop\bin\Debug\PCLStorage.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\John\Source\Repos\MyShoppette\MyShop\bin\Debug\System.Net.Http.dll] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Threading.Tasks.dll] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.IO" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="PCLStorage" culture="neutral" publicKeyToken="286fe515a2c35b64" /><bindingRedirect oldVersion="0.0.0.0-1.0.2.0" newVersion="1.0.2.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Threading.Tasks" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
2>    Processing: obj\Debug\res\layout\tabs.xml
2>    Processing: obj\Debug\res\layout\toolbar.xml
2>    Processing: obj\Debug\res\values\colors.xml
2>    Processing: obj\Debug\res\values\styles.xml
2>    Processing: obj\Debug\res\values-v21\styles.xml
2>    Processing: C:\Users\John\Source\Repos\MyShoppette\MyShop.Android\obj\Debug\__library_projects__\PCLStorage\library_project_imports\res\values\strings.xml
2>    Processing: C:\Users\John\Source\Repos\MyShoppette\MyShop.Android\obj\Debug\__library_projects__\PCLStorage\library_project_imports\res\values\strings.xml
2>  MyShop.Android -> C:\Users\John\Source\Repos\MyShoppette\MyShop.Android\bin\Debug\MyShop.Droid.dll
2>  No way to resolve conflict between "PCLStorage, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64" and "PCLStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64". Choosing "PCLStorage, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64" arbitrarily.
2>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Net.Primitives.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\John\Source\Repos\MyShoppette\MyShop\bin\Debug\System.Net.Http.dll] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Threading.Tasks.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "6.0.0.0" [] to Version "8.0.0.0" [C:\Users\John\Source\Repos\MyShoppette\packages\Newtonsoft.Json.8.0.3\lib\portable-net40+sl5+wp80+win8+wpa81\Newtonsoft.Json.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "PCLStorage, Culture=neutral, PublicKeyToken=286fe515a2c35b64" from Version "1.0.0.0" [] to Version "1.0.2.0" [C:\Users\John\Source\Repos\MyShoppette\MyShop\bin\Debug\PCLStorage.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "PCLStorage.Abstractions, Culture=neutral, PublicKeyToken=286fe515a2c35b64" from Version "1.0.0.0" [] to Version "1.0.2.0" [C:\Users\John\Source\Repos\MyShoppette\packages\PCLStorage.1.0.2\lib\monoandroid\PCLStorage.Abstractions.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\John\Source\Repos\MyShoppette\MyShop\bin\Debug\System.Net.Http.Primitives.dll] to Version "4.2.29.0" [C:\Users\John\Source\Repos\MyShoppette\packages\Microsoft.Net.Http.2.2.29\lib\monoandroid\System.Net.Http.Primitives.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.IO.dll] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1904,3): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Threading.Tasks" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="PCLStorage" culture="neutral" publicKeyToken="286fe515a2c35b64" /><bindingRedirect oldVersion="0.0.0.0-1.0.2.0" newVersion="1.0.2.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="PCLStorage.Abstractions" culture="neutral" publicKeyToken="286fe515a2c35b64" /><bindingRedirect oldVersion="0.0.0.0-1.0.2.0" newVersion="1.0.2.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.IO" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
2>    Processing: obj\Debug\res\layout\tabs.xml
2>    Processing: obj\Debug\res\layout\toolbar.xml
2>    Processing: obj\Debug\res\values\colors.xml
2>    Processing: obj\Debug\res\values\styles.xml
2>    Processing: obj\Debug\res\values-v21\styles.xml
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

The actual Error List is:
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\stores.json	0	IntelliSense	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	13	IntelliSense	Active
Error	CS0103	The name 'PickerRating' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	17	IntelliSense	Active
Error	CS0103	The name 'PickerServiceType' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	18	IntelliSense	Active
Error	CS0103	The name 'PickerStore' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	20	IntelliSense	Active
Error	CS0103	The name 'PickerStore' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	35	IntelliSense	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs	13	IntelliSense	Active
Error	CS0103	The name 'ButtonFindStore' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs	15	IntelliSense	Active
Error	CS0103	The name 'HeroImage' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs	25	IntelliSense	Active
Error	CS0103	The name 'ButtonLeaveFeedback' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml.cs	28	IntelliSense	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs	14	IntelliSense	Active
Error	CS0103	The name 'MyMap' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs	30	IntelliSense	Active
Error	CS0103	The name 'MyMap' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml.cs	32	IntelliSense	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StoresPage.xaml.cs	18	IntelliSense	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml	0	IntelliSense	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\HomePage.xaml	0	IntelliSense	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StorePage.xaml	0	IntelliSense	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\StoresPage.xaml	0	IntelliSense	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackListPage.xaml	0	IntelliSense	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackListPage.xaml.cs	14	IntelliSense	Active
Error	CS0103	The name 'FeedbackList' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackListPage.xaml.cs	16	IntelliSense	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackPage.xaml	0	IntelliSense	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackPage.xaml.cs	15	IntelliSense	Active
Error	CS0103	The name 'ButtonCall' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\FeedbackPage.xaml.cs	19	IntelliSense	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\HomePage.xaml	0	IntelliSense	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\HomePage.xaml.cs	12	IntelliSense	Active
Error	CS0103	The name 'ButtonManage' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\HomePage.xaml.cs	14	IntelliSense	Active
Error	CS0103	The name 'ButtonFeedback' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\HomePage.xaml.cs	19	IntelliSense	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\StoresPage.xaml	0	IntelliSense	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\StoresPage.xaml.cs	14	IntelliSense	Active
Error	CS0103	The name 'NewStore' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\StoresPage.xaml.cs	17	IntelliSense	Active
Error	CS0103	The name 'StoreList' does not exist in the current context	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\Views\StoresPage.xaml.cs	22	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\FeedbackViewModel.cs	29	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\FeedbackViewModel.cs	81	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\ViewModels\StoresViewModel.cs	105	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppette\MyShop\Views\FeedbackPage.xaml.cs	37	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\ViewModels\FeedbackListViewModel.cs	57	IntelliSense	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShopAdmin	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin\ViewModels\FeedbackListViewModel.cs	98	IntelliSense	Active
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	MyShop.UWP		1	IntelliSense	Active
Warning		Project must install nuget package Microsoft.Bcl, version=1.1.10. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.	MyShop.UWP			Build	
Warning		Could not find SDK "SQLite.UWP.2015, Version=3.12.2".	MyShop.UWP			Build	
Warning		Project must install nuget package Microsoft.Net.Http, version=2.2.29. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.	MyShop.UWP			Build	
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	MyShopAdmin.Android		1	IntelliSense	Active
Warning		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.	MyShopAdmin.Android	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin.Android\MyShopAdmin.Android.csproj	276	Build	
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	MyShopAdmin.iOS		1	IntelliSense	Active
Warning		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.	MyShopAdmin.iOS	C:\Users\John\Source\Repos\MyShoppette\MyShopAdmin.iOS\MyShopAdmin.iOS.csproj	257	Build

**Comment by VashJuan** [comment]
I'm also getting a dialog titled, "Monitor" which states: Failed to load the JNI shared library "C:\Program Files (x86)\Java\jdk1.7.0_55\bin\..\jre\bin\client\jvm.dll", if that sounds pertinent.

**Comment by jamesmontemagno** [comment]
Are you able to restore your nuget packages? Right click on the solution and hit restore nuget packages.

**Comment by VashJuan** [comment]
Thanks for helping! I selected the top solution, and then did a restore, but I still have the same apparent issues. 

Zeroing in on a couple of them, in the following screenshot it seems that I've the package installed, but the build warning indicates I don't. Hmmmm.
![5-13-2016 at 2 04 00 pm](https://cloud.githubusercontent.com/assets/8594671/15263619/90178dcc-1920-11e6-87b3-68485c923a7b.jpg)
or this one...
![5-13-2016 at 3 32 50 pm](https://cloud.githubusercontent.com/assets/8594671/15263963/4e648008-1923-11e6-9e02-bc661cc2af33.jpg)

Is the issue that nuget is not reinstalling the package properly, or that the project expects a different version than what I have, or something else? Looking at the comments, it seems that nuget is fairly flaky in ensuring the proper packages are properly installed?

**Comment by jamesmontemagno** [comment]
Can you change your error list setting to just "Build", not "Build + Intellisense"

The warnings are all fine to ignore.

**Comment by VashonSoftware** [comment]
Wow, that is much less intimidating!

No errors, just these warnings now:
Severity	Code	Description	Project	File	Line	Source	Suppression State
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppe\MyShop\ViewModels\FeedbackViewModel.cs	29	Build	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppe\MyShop\ViewModels\FeedbackViewModel.cs	81	Build	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppe\MyShop\ViewModels\StoresViewModel.cs	105	Build	Active
Warning	CS0168	The variable 'ex' is declared but never used	MyShop	C:\Users\John\Source\Repos\MyShoppe\MyShop\Views\FeedbackPage.xaml.cs	37	Build	Active
Warning		Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: Microsoft.Bcl, Microsoft.Net.Http, SQLitePCL	MyShop		0	Build	
Warning		Project must install nuget package Microsoft.Net.Http, version=2.2.29. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.	MyShop.UWP			Build	
Warning		Could not find SDK "SQLite.UWP.2015, Version=3.12.2".	MyShop.UWP			Build	
Warning		Project must install nuget package Microsoft.Bcl, version=1.1.10. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.	MyShop.UWP			Build	
Warning		Failed to resolve all project references for 'MyShop.UWP'. The package restore result for 'C:\Users\John\Source\Repos\MyShoppe\MyShop.UWP\MyShop.UWP.csproj' may be incomplete.			0	Build

**Comment by VashonSoftware** [comment]
Well, I'm not sure what changed, but I did get it up and running -- at least until MyShoppe told me I need to install Google Play Services on my emulator...

Certainly doing the RESTORE NEGET PACKAGES helped, and it may have helped to use a late model Android device, and I also got the backend going 1st, and maybe there was something else, but I think those werer the most likely culprits.

THANKS for your help and I'll get back if I can detail any of this better with some experiments/tests.

**Comment by VashJuan** [comment]
Coming in with a different username...
