### ISSUE TITLE
StoresViewModel.cs: Infinite recursive error

### ISSUE THREAD

**Issue by reader-man** [jamesmontemagno/MyShoppe#16]
Hi,
Thanks for the very nice example.
The following code in "StoresViewModel.cs":
```
        Store selectedStore;
        public Store SelectedStore
        {
            get { return selectedStore; }
            set
            {
                selectedStore = value;
                OnPropertyChanged("SelectedStore");
                if (selectedStore == null)
                    return;

                if (ItemSelected == null)
                {
                    page.Navigation.PushAsync(new StorePage(selectedStore));
                    SelectedStore = null;
                }
                else
                {
                    ItemSelected.Invoke(selectedStore);
                }
            }
        }

```

**As you can see:**
SelectedStore = null;
Has the capital "**S**", which i think you meant it to be small "**s**", to refer to the private field, not the public property, as the current code, makes the app recurs infinitely.

I am not pushing on a coding style, but having the following, make readability clearer in my point of view, but still thanks on the good example:

```
        Store _selectedStore;
        public Store SelectedStore
        {
            get { return _selectedStore; }
            set
            {
                _selectedStore = value;
                OnPropertyChanged("SelectedStore");
                if (_selectedStore == null)
                    return;

                if (ItemSelected == null)
                {
                    if (Language.Singleton.Current == Language.C_Lang_En)
                        page.Navigation.PushAsync(new StorePage(_selectedStore));
                    else
                        page.Navigation.PushAsync(new StorePageAr(_selectedStore));

                    _selectedStore = null;
                }
                else
                {
                    ItemSelected.Invoke(_selectedStore);
                }
            }
        }
```

**Comment by Stayrony** [comment]
I have the same problem too. I can't navigate to StorePage.
App isn't respond. I change to 's', but it still navigate.
Did you @reader-man figure out with it?

**Comment by reader-man** [comment]
@Stayrony, well i changed the code to:
        Store _selectedStore;
        public Store SelectedStore
        {
            get { return _selectedStore; }
            set
            {
                _selectedStore = value;
                OnPropertyChanged("SelectedStore");
                if (_selectedStore == null)
                    return;

                if (ItemSelected == null)
                {
                    if (Language.Singleton.Current == Language.C_Lang_En)
                        page.Navigation.PushAsync(new StorePage(_selectedStore));
                    else
                        page.Navigation.PushAsync(new StorePageAr(_selectedStore));

                    _selectedStore = null;
                }
                else
                {
                    ItemSelected.Invoke(_selectedStore);
                }
            }
        }

and now its working perfect with me.
but also, try to clean solution, and rebuild it, to make sure that its using the new change.

**Comment by reader-man** [comment]
@Stayrony it looks that some times it works and others, it doesn't.
After two days of invetigation, found that in "StoreViewModel.cs":
```
       public StoreViewModel(Store store, Page page) : base(page)
        {
			this.Store = store;
        }
```

that the "this.Store = store" is called twice, and checking the stack strace, it was becuase of this in "App.cs":

```
       public static StoreViewModel StoreViewModel
        { 
            get
            {
                if (storeViewModel != null)
                    return storeViewModel;
                return null;
                //var offline = new OfflineDataStore();
                //var task = offline.GetStoresAsync();
                //task.Wait();
                //var store = task.Result.First();
                //storeViewModel = new StoreViewModel(store, null);
                //return storeViewModel;
            }
        }
```

    and as you can see, that most of that function was comented, and now its working.

**Comment by jamesmontemagno** [comment]
My code is correct..

When you set it to null it will deselect the item from the list as I intended.

then when it comes back in it sets it to null and return:
```
if (selectedStore == null)
                    return;
```

**Comment by reader-man** [comment]
@jamesmontemagno Yes, you are correct about the:
```
if (selectedStore == null)
                    return;
```

But, have u checked the code in "App.cs":

```
       public static StoreViewModel StoreViewModel
        { 
            get
            {
                if (storeViewModel != null)
                    return storeViewModel;
                return null;
                //var offline = new OfflineDataStore();
                //var task = offline.GetStoresAsync();
                //task.Wait();
                //var store = task.Result.First();
                //storeViewModel = new StoreViewModel(store, null);
                //return storeViewModel;
            }
        }

```

As i think, the culprit is there.

**Comment by jamesmontemagno** [comment]
That code is for design time data only and shouldn't be used at all during running the app. Here I will put in a flag.

**Comment by reader-man** [comment]
Thanks, as this is being run in normal execution time, not just in design time.
