### ISSUE TITLE
AzureDataStore never gets used

### ISSUE THREAD

**Issue by MrSco** [jamesmontemagno/MyShoppe#17]
Thanks for posting this awesome example. I got it working as is but i'm having some issues when i start to change the backend...

I created my own mobile app backend in azure following the steps provided, but while debugging only the OfflineDataStore gets called and so only the contents of the stores.json file is read. It looks like dataStore = DependencyService.Get<IDataStore>(); always returns the OfflineDataStore... am I missing something? any help would be awesome.

thanks again.

**Comment by jamesmontemagno** [comment]
You need to comment in:
https://github.com/jamesmontemagno/MyShoppe/blob/master/MyShop/Services/AzureDataStore.cs#L16

And comment out:
https://github.com/jamesmontemagno/MyShoppe/blob/master/MyShop/Services/OfflineDataStore.cs#L11
