### ISSUE TITLE
Can't build app on my iPhone, just test only simulator.

### ISSUE THREAD

**Issue by uthens** [jamesmontemagno/MyShoppe#2]
I try to build on Myshop.iOS, but don't have my devices show on Xamarin.
I can tested only simulator.

How i can build your project to my iPhone ?

**Comment by jamesmontemagno** [comment]
Here you go: https://developer.xamarin.com/guides/ios/getting_started/installation/device_provisioning/

**Comment by uthens** [comment]
Thanks you so much :+1:
