### ISSUE TITLE
Linked resource does NOT exist

### ISSUE THREAD

**Issue by apuokenas** [jamesmontemagno/MyShoppe#23]
Regarding the string "MyShoppe/MyShopApp_Web/MyShopAppService/DataObjects" (linked to https://github.com/jamesmontemagno/MyShoppe/tree/master/MyShopApp_Web/MyShopAppService/DataObjects) found in [README](https://github.com/jamesmontemagno/MyShoppe/blob/master/README.md): it resolves into 404. Could you please update the documentation and the project itself? There is no MyShopApp_Web/MyShopAppService part.

**Comment by jamesmontemagno** [comment]
Fixed
