### ISSUE TITLE
BaseViewModel Wrong

### ISSUE THREAD

**Issue by zjxeditor** [jamesmontemagno/MyShoppe#5]
In file "StoreViewModel.cs" of project "MyShopAdmin", the "BaseViewModel" base class take "page" as the constructor  parameter. However, "BaseViewModel" in "MvvmHelper" have no such constructor. So I cannot build the Admin application.

![capture](https://cloud.githubusercontent.com/assets/16350631/13468050/d6387294-e0db-11e5-8105-34735bb74f5f.JPG)

**Comment by zjxeditor** [comment]
OMG, the real BaseViewModel locates in the MyShop(Portable) project.

**Comment by zjxeditor** [comment]
And we should change the BaseViewModel into ViewModelBase.

**Comment by jamesmontemagno** [comment]
Fixing up, thanks
