### ISSUE TITLE
Azure package issue

### ISSUE THREAD

**Issue by zjxeditor** [jamesmontemagno/MyShoppe#6]
I think we should replace the package "WindowsAzure.MobileServices.SQLiteStore" with "Microsoft.Azure.Mobile.Client". I always get "bad request (400)" when fetching data from the database. While, after this replacement, everything is fine. I don't know the reason.

**Comment by jamesmontemagno** [comment]
They made a lot of changes for final release, let me look into it.

**Comment by zjxeditor** [comment]
It take a total day for me to make all the stuff work fine.

**Comment by jamesmontemagno** [comment]
Fixed up
